# Generated by Django 6.0.1 on 2026-01-29 10:09

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kpt', '0002_alter_category_is_active_alter_post_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='text',
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name='Treść artykułu'),
        ),
    ]
