# Generated by Django 6.0.1 on 2026-01-29 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kpt', '0003_alter_post_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='create_date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='create_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
